package com.mappingroadconditions;
import java.io.InputStream;
import java.io.ObjectInputStream;
//import android.util.Log;
import weka.classifiers.Classifier;
import weka.core.Attribute;
import weka.core.FastVector;
import weka.core.Instance;
import weka.core.Instances;

public class LoadClassifier {
	public static Classifier c = null;
	public static Attribute Attribute1 = new Attribute("Std_Y");
	public static Attribute Attribute2 = new Attribute("Std_Z"); 
	public static Attribute Attribute3 = new Attribute("Std_X"); 
	public static Attribute Attribute4 = new Attribute("Pt1stdaway_Y"); 
	public static Attribute Attribute5 = new Attribute("Pt1stdaway_Z"); 
	public static Attribute Attribute6 = new Attribute("Pt1stdaway_X"); 
	public static Attribute Attribute7 = new Attribute("Pt2stdaway_X"); 
	public static Attribute Attribute8 = new Attribute("Pt2stdaway_Y"); 
	public static Attribute Attribute9 = new Attribute("Pt2stdaway_Z"); 
	public static Attribute Attribute10 = new Attribute("Maxima_Y"); 
	public static Attribute Attribute11 = new Attribute("Maxima_Z"); 
	public static Attribute Attribute12 = new Attribute("Maxima_X"); 
	public static Attribute Attribute13 = new Attribute("Minima_Z"); 
	public static Attribute Attribute14 = new Attribute("Minima_Y"); 
	public static Attribute Attribute15 = new Attribute("Minima_X"); 
	public static Attribute Attribute16 = new Attribute("MinSpeed"); 
	public static Attribute Attribute17 = new Attribute("MaxSpeed"); 
	public static Attribute Attribute18 = new Attribute("FilMaxima_Y"); 
	public static Attribute Attribute19 = new Attribute("FilMaxima_Z"); 
	public static Attribute Attribute20 = new Attribute("FilMaxima_X"); 
	public static Attribute Attribute21 = new Attribute("FilMinima_Y"); 
	public static Attribute Attribute22 = new Attribute("FilMinima_Z"); 
	public static Attribute Attribute23 = new Attribute("FilMinima_X"); 
	public static Attribute Attribute24 = new Attribute("FilStd_Z"); 
	public static Attribute Attribute25 = new Attribute("FilStd_X"); 
	public static Attribute Attribute26 = new Attribute("FilStd_Y"); 
	public static Attribute Attribute27 = new Attribute("FilPt1stdaway_Y"); 
	public static Attribute Attribute28 = new Attribute("FilPt1stdaway_Z"); 
	public static Attribute Attribute29 = new Attribute("FilPt2stdaway_X"); 
	public static Attribute Attribute30 = new Attribute("FilPt2stdaway_Y"); 
	public static Attribute Attribute31 = new Attribute("FilPt2stdaway_Z"); 
	public static Attribute Attribute32 = new Attribute("FilPt1stdaway_X"); 
	public static Attribute Attribute33 = new Attribute("AvSpeed"); 
	public static Attribute Attribute34 = new Attribute("FilFFT_Z_1"); 
	public static Attribute Attribute35 = new Attribute("FilFFT_Z_2"); 
	public static Attribute Attribute36 = new Attribute("FilFFT_Z_3"); 
	public static Attribute Attribute37 = new Attribute("FilFFT_Z_4"); 
	public static Attribute Attribute38 = new Attribute("FilFFT_Z_5"); 
	public static Attribute Attribute39 = new Attribute("FilFFT_Z_6"); 
	public static Attribute Attribute40 = new Attribute("FilFFT_Z_7"); 
	public static Attribute Attribute41 = new Attribute("FilFFT_Z_8"); 
	public static Attribute Attribute42 = new Attribute("FilFFT_Z_9"); 
	public static Attribute Attribute43 = new Attribute("FilFFT_Z_10"); 
	public static Attribute Attribute44 = new Attribute("FilFFT_Z_11"); 
	public static Attribute Attribute45 = new Attribute("FilFFT_Z_12"); 
	public static Attribute Attribute46 = new Attribute("FilFFT_Z_13"); 
	public static Attribute Attribute47 = new Attribute("FilFFT_Z_14"); 
	public static Attribute Attribute48 = new Attribute("FilFFT_Z_15"); 
	public static Attribute Attribute49 = new Attribute("FilFFT_Z_16"); 
	public static Attribute Attribute50 = new Attribute("FilFFT_Z_17"); 
	public static Attribute Attribute51 = new Attribute("FilFFT_Z_18"); 
	public static Attribute Attribute52 = new Attribute("FilFFT_Z_19"); 
	public static Attribute Attribute53 = new Attribute("FilFFT_Z_20"); 
	public static Attribute Attribute54 = new Attribute("FilFFT_Z_21"); 
	public static Attribute Attribute55 = new Attribute("FilFFT_Z_22"); 
	public static Attribute Attribute56 = new Attribute("FilFFT_Z_23"); 
	public static Attribute Attribute57 = new Attribute("FilFFT_Z_24"); 
	public static Attribute Attribute58 = new Attribute("FilFFT_Z_25"); 
	public static Attribute Attribute59 = new Attribute("FilFFT_Z_26"); 
	public static Attribute Attribute60 = new Attribute("FilFFT_Z_27"); 
	public static Attribute Attribute61 = new Attribute("FilFFT_Z_28"); 
	public static Attribute Attribute62 = new Attribute("FilFFT_Z_29"); 
	public static Attribute Attribute63 = new Attribute("FilFFT_Z_30"); 
	public static Attribute Attribute64 = new Attribute("FilFFT_Z_31"); 
	public static Attribute Attribute65 = new Attribute("FilFFT_Z_32"); 
	public static Attribute Attribute66 = new Attribute("FilFFT_Z_33"); 
	public static Attribute Attribute67 = new Attribute("FilFFT_Z_34"); 
	public static Attribute Attribute68 = new Attribute("FilFFT_Z_35"); 
	public static Attribute Attribute69 = new Attribute("FilFFT_Z_36"); 
	public static Attribute Attribute70 = new Attribute("FilFFT_Z_37"); 
	public static Attribute Attribute71 = new Attribute("FilFFT_Z_38"); 
	public static Attribute Attribute72 = new Attribute("FilFFT_Z_39"); 
	public static Attribute Attribute73 = new Attribute("FilFFT_Z_40"); 
	public static Attribute Attribute74 = new Attribute("FilFFT_Z_41"); 
	public static Attribute Attribute75 = new Attribute("FilFFT_Z_42"); 
	public static Attribute Attribute76 = new Attribute("FilFFT_Z_43"); 
	public static Attribute Attribute77 = new Attribute("FilFFT_Z_44"); 
	public static Attribute Attribute78 = new Attribute("FilFFT_Z_45"); 
	public static Attribute Attribute79 = new Attribute("FilFFT_Z_46"); 
	public static Attribute Attribute80 = new Attribute("FilFFT_Z_47"); 
	public static Attribute Attribute81 = new Attribute("FFT_X_1"); 
	public static Attribute Attribute82 = new Attribute("FFT_X_2"); 
	public static Attribute Attribute83 = new Attribute("FFT_X_3"); 
	public static Attribute Attribute84 = new Attribute("FFT_X_4"); 
	public static Attribute Attribute85 = new Attribute("FFT_X_5"); 
	public static Attribute Attribute86 = new Attribute("FFT_X_6"); 
	public static Attribute Attribute87 = new Attribute("FFT_X_7"); 
	public static Attribute Attribute88 = new Attribute("FFT_X_8"); 
	public static Attribute Attribute89 = new Attribute("FFT_X_9"); 
	public static Attribute Attribute90 = new Attribute("FFT_X_10"); 
	public static Attribute Attribute91 = new Attribute("FFT_X_11"); 
	public static Attribute Attribute92 = new Attribute("FFT_X_12"); 
	public static Attribute Attribute93 = new Attribute("FFT_X_13"); 
	public static Attribute Attribute94 = new Attribute("FFT_X_14"); 
	public static Attribute Attribute95 = new Attribute("FFT_X_15"); 
	public static Attribute Attribute96 = new Attribute("FFT_X_16"); 
	public static Attribute Attribute97 = new Attribute("FFT_X_17"); 
	public static Attribute Attribute98 = new Attribute("FFT_X_18"); 
	public static Attribute Attribute99 = new Attribute("FFT_X_19"); 
	public static Attribute Attribute100 = new Attribute("FFT_X_20"); 
	public static Attribute Attribute101 = new Attribute("FFT_X_21"); 
	public static Attribute Attribute102 = new Attribute("FFT_X_22"); 
	public static Attribute Attribute103 = new Attribute("FFT_X_23"); 
	public static Attribute Attribute104 = new Attribute("FFT_X_24"); 
	public static Attribute Attribute105 = new Attribute("FFT_X_25"); 
	public static Attribute Attribute106 = new Attribute("FFT_X_26"); 
	public static Attribute Attribute107 = new Attribute("FFT_X_27"); 
	public static Attribute Attribute108 = new Attribute("FFT_X_28"); 
	public static Attribute Attribute109 = new Attribute("FFT_X_29"); 
	public static Attribute Attribute110 = new Attribute("FFT_X_30"); 
	public static Attribute Attribute111 = new Attribute("FFT_X_31"); 
	public static Attribute Attribute112 = new Attribute("FFT_X_32"); 
	public static Attribute Attribute113 = new Attribute("FFT_X_33"); 
	public static Attribute Attribute114 = new Attribute("FFT_X_34"); 
	public static Attribute Attribute115 = new Attribute("FFT_X_35"); 
	public static Attribute Attribute116 = new Attribute("FFT_X_36"); 
	public static Attribute Attribute117 = new Attribute("FFT_X_37"); 
	public static Attribute Attribute118 = new Attribute("FFT_X_38"); 
	public static Attribute Attribute119 = new Attribute("FFT_X_39"); 
	public static Attribute Attribute120 = new Attribute("FFT_X_40"); 
	public static Attribute Attribute121 = new Attribute("FFT_X_41"); 
	public static Attribute Attribute122 = new Attribute("FFT_X_42"); 
	public static Attribute Attribute123 = new Attribute("FFT_X_43"); 
	public static Attribute Attribute124 = new Attribute("FFT_X_44"); 
	public static Attribute Attribute125 = new Attribute("FFT_X_45"); 
	public static Attribute Attribute126 = new Attribute("FFT_X_46"); 
	public static Attribute Attribute127 = new Attribute("FFT_X_47"); 
	public static Attribute Attribute128 = new Attribute("FFT_X_48"); 
	public static Attribute Attribute129 = new Attribute("FFT_X_49"); 
	public static Attribute Attribute130 = new Attribute("FilFFT_Y_1"); 
	public static Attribute Attribute131 = new Attribute("FilFFT_Y_2"); 
	public static Attribute Attribute132 = new Attribute("FilFFT_Y_3"); 
	public static Attribute Attribute133 = new Attribute("FilFFT_Y_4"); 
	public static Attribute Attribute134 = new Attribute("FilFFT_Y_5"); 
	public static Attribute Attribute135 = new Attribute("FilFFT_Y_6"); 
	public static Attribute Attribute136 = new Attribute("FilFFT_Y_7"); 
	public static Attribute Attribute137 = new Attribute("FilFFT_Y_8"); 
	public static Attribute Attribute138 = new Attribute("FilFFT_Y_9"); 
	public static Attribute Attribute139 = new Attribute("FilFFT_Y_10"); 
	public static Attribute Attribute140 = new Attribute("FilFFT_Y_11"); 
	public static Attribute Attribute141 = new Attribute("FilFFT_Y_12"); 
	public static Attribute Attribute142 = new Attribute("FilFFT_Y_13"); 
	public static Attribute Attribute143 = new Attribute("FilFFT_Y_14"); 
	public static Attribute Attribute144 = new Attribute("FilFFT_Y_15"); 
	public static Attribute Attribute145 = new Attribute("FilFFT_Y_16"); 
	public static Attribute Attribute146 = new Attribute("FilFFT_Y_17"); 
	public static Attribute Attribute147 = new Attribute("FilFFT_Y_18"); 
	public static Attribute Attribute148 = new Attribute("FilFFT_Y_19"); 
	public static Attribute Attribute149 = new Attribute("FilFFT_Y_20"); 
	public static Attribute Attribute150 = new Attribute("FilFFT_Y_21"); 
	public static Attribute Attribute151 = new Attribute("FilFFT_Y_22"); 
	public static Attribute Attribute152 = new Attribute("FilFFT_Y_23"); 
	public static Attribute Attribute153 = new Attribute("FilFFT_Y_24"); 
	public static Attribute Attribute154 = new Attribute("FilFFT_Y_25"); 
	public static Attribute Attribute155 = new Attribute("FilFFT_Y_26"); 
	public static Attribute Attribute156 = new Attribute("FilFFT_Y_27"); 
	public static Attribute Attribute157 = new Attribute("FilFFT_Y_28"); 
	public static Attribute Attribute158 = new Attribute("FilFFT_Y_29"); 
	public static Attribute Attribute159 = new Attribute("FilFFT_Y_30"); 
	public static Attribute Attribute160 = new Attribute("FilFFT_Y_31"); 
	public static Attribute Attribute161 = new Attribute("FilFFT_Y_32"); 
	public static Attribute Attribute162 = new Attribute("FilFFT_Y_33"); 
	public static Attribute Attribute163 = new Attribute("FilFFT_Y_34"); 
	public static Attribute Attribute164 = new Attribute("FilFFT_Y_35"); 
	public static Attribute Attribute165 = new Attribute("FilFFT_Y_36"); 
	public static Attribute Attribute166 = new Attribute("FilFFT_Y_37"); 
	public static Attribute Attribute167 = new Attribute("FilFFT_Y_38"); 
	public static Attribute Attribute168 = new Attribute("FilFFT_Y_39"); 
	public static Attribute Attribute169 = new Attribute("FilFFT_Y_40"); 
	public static Attribute Attribute170 = new Attribute("FilFFT_Y_41"); 
	public static Attribute Attribute171 = new Attribute("FilFFT_Y_42"); 
	public static Attribute Attribute172 = new Attribute("FilFFT_Y_43"); 
	public static Attribute Attribute173 = new Attribute("FilFFT_Y_44"); 
	public static Attribute Attribute174 = new Attribute("FilFFT_Y_45"); 
	public static Attribute Attribute175 = new Attribute("FilFFT_Y_46"); 
	public static Attribute Attribute176 = new Attribute("FilFFT_Y_47"); 
	public static Attribute Attribute177 = new Attribute("FilFFT_Y_48"); 
	public static Attribute Attribute178 = new Attribute("FilFFT_Y_49"); 
	public static Attribute Attribute179 = new Attribute("FilFFT_X_1"); 
	public static Attribute Attribute180 = new Attribute("FilFFT_X_2"); 
	public static Attribute Attribute181 = new Attribute("FilFFT_X_3"); 
	public static Attribute Attribute182 = new Attribute("FilFFT_X_4"); 
	public static Attribute Attribute183 = new Attribute("FilFFT_X_5"); 
	public static Attribute Attribute184 = new Attribute("FilFFT_X_6"); 
	public static Attribute Attribute185 = new Attribute("FilFFT_X_7"); 
	public static Attribute Attribute186 = new Attribute("FilFFT_X_8"); 
	public static Attribute Attribute187 = new Attribute("FilFFT_X_9"); 
	public static Attribute Attribute188 = new Attribute("FilFFT_X_10"); 
	public static Attribute Attribute189 = new Attribute("FilFFT_X_11"); 
	public static Attribute Attribute190 = new Attribute("FilFFT_X_12"); 
	public static Attribute Attribute191 = new Attribute("FilFFT_X_13"); 
	public static Attribute Attribute192 = new Attribute("FilFFT_X_14"); 
	public static Attribute Attribute193 = new Attribute("FilFFT_X_15"); 
	public static Attribute Attribute194 = new Attribute("FilFFT_X_16"); 
	public static Attribute Attribute195 = new Attribute("FilFFT_X_17"); 
	public static Attribute Attribute196 = new Attribute("FilFFT_X_18"); 
	public static Attribute Attribute197 = new Attribute("FilFFT_X_19"); 
	public static Attribute Attribute198 = new Attribute("FilFFT_X_20"); 
	public static Attribute Attribute199 = new Attribute("FilFFT_X_21"); 
	public static Attribute Attribute200 = new Attribute("FilFFT_X_22"); 
	public static Attribute Attribute201 = new Attribute("FilFFT_X_23"); 
	public static Attribute Attribute202 = new Attribute("FilFFT_X_24"); 
	public static Attribute Attribute203 = new Attribute("FilFFT_X_25"); 
	public static Attribute Attribute204 = new Attribute("FilFFT_X_26"); 
	public static Attribute Attribute205 = new Attribute("FilFFT_X_27"); 
	public static Attribute Attribute206 = new Attribute("FilFFT_X_28"); 
	public static Attribute Attribute207 = new Attribute("FilFFT_X_29"); 
	public static Attribute Attribute208 = new Attribute("FilFFT_X_30"); 
	public static Attribute Attribute209 = new Attribute("FilFFT_X_31"); 
	public static Attribute Attribute210 = new Attribute("FilFFT_X_32"); 
	public static Attribute Attribute211 = new Attribute("FilFFT_X_33"); 
	public static Attribute Attribute212 = new Attribute("FilFFT_X_34"); 
	public static Attribute Attribute213 = new Attribute("FilFFT_X_35"); 
	public static Attribute Attribute214 = new Attribute("FilFFT_X_36"); 
	public static Attribute Attribute215 = new Attribute("FilFFT_X_37"); 
	public static Attribute Attribute216 = new Attribute("FilFFT_X_38"); 
	public static Attribute Attribute217 = new Attribute("FilFFT_X_39"); 
	public static Attribute Attribute218 = new Attribute("FilFFT_X_40"); 
	public static Attribute Attribute219 = new Attribute("FilFFT_X_41"); 
	public static Attribute Attribute220 = new Attribute("FilFFT_X_42"); 
	public static Attribute Attribute221 = new Attribute("FilFFT_X_43"); 
	public static Attribute Attribute222 = new Attribute("FilFFT_X_44"); 
	public static Attribute Attribute223 = new Attribute("FilFFT_X_45"); 
	public static Attribute Attribute224 = new Attribute("FilFFT_X_46"); 
	public static Attribute Attribute225 = new Attribute("FilFFT_X_47"); 
	public static Attribute Attribute226 = new Attribute("FilFFT_X_48"); 
	public static Attribute Attribute227 = new Attribute("FFT_Y_1"); 
	public static Attribute Attribute228 = new Attribute("FFT_Y_2"); 
	public static Attribute Attribute229 = new Attribute("FFT_Y_3"); 
	public static Attribute Attribute230 = new Attribute("FFT_Y_4"); 
	public static Attribute Attribute231 = new Attribute("FFT_Y_5"); 
	public static Attribute Attribute232 = new Attribute("FFT_Y_6"); 
	public static Attribute Attribute233 = new Attribute("FFT_Y_7"); 
	public static Attribute Attribute234 = new Attribute("FFT_Y_8"); 
	public static Attribute Attribute235 = new Attribute("FFT_Y_9"); 
	public static Attribute Attribute236 = new Attribute("FFT_Y_10"); 
	public static Attribute Attribute237 = new Attribute("FFT_Y_11"); 
	public static Attribute Attribute238 = new Attribute("FFT_Y_12"); 
	public static Attribute Attribute239 = new Attribute("FFT_Y_13"); 
	public static Attribute Attribute240 = new Attribute("FFT_Y_14"); 
	public static Attribute Attribute241 = new Attribute("FFT_Y_15"); 
	public static Attribute Attribute242 = new Attribute("FFT_Y_16"); 
	public static Attribute Attribute243 = new Attribute("FFT_Y_17"); 
	public static Attribute Attribute244 = new Attribute("FFT_Y_18"); 
	public static Attribute Attribute245 = new Attribute("FFT_Y_19"); 
	public static Attribute Attribute246 = new Attribute("FFT_Y_20"); 
	public static Attribute Attribute247 = new Attribute("FFT_Y_21"); 
	public static Attribute Attribute248 = new Attribute("FFT_Y_22"); 
	public static Attribute Attribute249 = new Attribute("FFT_Y_23"); 
	public static Attribute Attribute250 = new Attribute("FFT_Y_24"); 
	public static Attribute Attribute251 = new Attribute("FFT_Y_25"); 
	public static Attribute Attribute252 = new Attribute("FFT_Y_26"); 
	public static Attribute Attribute253 = new Attribute("FFT_Y_27"); 
	public static Attribute Attribute254 = new Attribute("FFT_Y_28"); 
	public static Attribute Attribute255 = new Attribute("FFT_Y_29"); 
	public static Attribute Attribute256 = new Attribute("FFT_Y_30"); 
	public static Attribute Attribute257 = new Attribute("FFT_Y_31"); 
	public static Attribute Attribute258 = new Attribute("FFT_Y_32"); 
	public static Attribute Attribute259 = new Attribute("FFT_Y_33"); 
	public static Attribute Attribute260 = new Attribute("FFT_Y_34"); 
	public static Attribute Attribute261 = new Attribute("FFT_Y_35"); 
	public static Attribute Attribute262 = new Attribute("FFT_Y_36"); 
	public static Attribute Attribute263 = new Attribute("FFT_Y_37"); 
	public static Attribute Attribute264 = new Attribute("FFT_Y_38"); 
	public static Attribute Attribute265 = new Attribute("FFT_Y_39"); 
	public static Attribute Attribute266 = new Attribute("FFT_Y_40"); 
	public static Attribute Attribute267 = new Attribute("FFT_Y_41"); 
	public static Attribute Attribute268 = new Attribute("FFT_Y_42"); 
	public static Attribute Attribute269 = new Attribute("FFT_Y_43"); 
	public static Attribute Attribute270 = new Attribute("FFT_Y_44"); 
	public static Attribute Attribute271 = new Attribute("FFT_Y_45"); 
	public static Attribute Attribute272 = new Attribute("FFT_Y_46"); 
	public static Attribute Attribute273 = new Attribute("FFT_Y_47"); 
	public static Attribute Attribute274 = new Attribute("FFT_Y_48"); 
	public static Attribute Attribute275 = new Attribute("FFT_Y_49"); 
	public static Attribute Attribute276 = new Attribute("FFT_Z_1"); 
	public static Attribute Attribute277 = new Attribute("FFT_Z_2"); 
	public static Attribute Attribute278 = new Attribute("FFT_Z_3"); 
	public static Attribute Attribute279 = new Attribute("FFT_Z_4"); 
	public static Attribute Attribute280 = new Attribute("FFT_Z_5"); 
	public static Attribute Attribute281 = new Attribute("FFT_Z_6"); 
	public static Attribute Attribute282 = new Attribute("FFT_Z_7"); 
	public static Attribute Attribute283 = new Attribute("FFT_Z_8"); 
	public static Attribute Attribute284 = new Attribute("FFT_Z_9"); 
	public static Attribute Attribute285 = new Attribute("FFT_Z_10"); 
	public static Attribute Attribute286 = new Attribute("FFT_Z_11"); 
	public static Attribute Attribute287 = new Attribute("FFT_Z_12"); 
	public static Attribute Attribute288 = new Attribute("FFT_Z_13"); 
	public static Attribute Attribute289 = new Attribute("FFT_Z_14"); 
	public static Attribute Attribute290 = new Attribute("FFT_Z_15"); 
	public static Attribute Attribute291 = new Attribute("FFT_Z_16"); 
	public static Attribute Attribute292 = new Attribute("FFT_Z_17"); 
	public static Attribute Attribute293 = new Attribute("FFT_Z_18"); 
	public static Attribute Attribute294 = new Attribute("FFT_Z_19"); 
	public static Attribute Attribute295 = new Attribute("FFT_Z_20"); 
	public static Attribute Attribute296 = new Attribute("FFT_Z_21"); 
	public static Attribute Attribute297 = new Attribute("FFT_Z_22"); 
	public static Attribute Attribute298 = new Attribute("FFT_Z_23"); 
	public static Attribute Attribute299 = new Attribute("FFT_Z_24"); 
	public static Attribute Attribute300 = new Attribute("FFT_Z_25"); 
	public static Attribute Attribute301 = new Attribute("FFT_Z_26"); 
	public static Attribute Attribute302 = new Attribute("FFT_Z_27"); 
	public static Attribute Attribute303 = new Attribute("FFT_Z_28"); 
	public static Attribute Attribute304 = new Attribute("FFT_Z_29"); 
	public static Attribute Attribute305 = new Attribute("FFT_Z_30"); 
	public static Attribute Attribute306 = new Attribute("FFT_Z_31"); 
	public static Attribute Attribute307 = new Attribute("FFT_Z_32"); 
	public static Attribute Attribute308 = new Attribute("FFT_Z_33"); 
	public static Attribute Attribute309 = new Attribute("FFT_Z_34"); 
	public static Attribute Attribute310 = new Attribute("FFT_Z_35"); 
	public static Attribute Attribute311 = new Attribute("FFT_Z_36"); 
	public static Attribute Attribute312 = new Attribute("FFT_Z_37"); 
	public static Attribute Attribute313 = new Attribute("FFT_Z_38"); 
	public static Attribute Attribute314 = new Attribute("FFT_Z_39"); 
	public static Attribute Attribute315 = new Attribute("FFT_Z_40"); 
	public static Attribute Attribute316 = new Attribute("FFT_Z_41"); 
	public static Attribute Attribute317 = new Attribute("FFT_Z_42"); 
	public static Attribute Attribute318 = new Attribute("FFT_Z_43"); 
	public static Attribute Attribute319 = new Attribute("FFT_Z_44"); 
	public static Attribute Attribute320 = new Attribute("FFT_Z_45"); 
	public static Attribute Attribute321 = new Attribute("FFT_Z_46"); 
	public static Attribute Attribute322 = new Attribute("FFT_Z_47"); 
	public static Attribute Attribute323 = new Attribute("FFT_Z_48"); 
	public static Attribute Attribute324 = new Attribute("FFT_Z_49"); 
	public static Attribute Attribute325 = new Attribute("MaxFFT_X"); 
	public static Attribute Attribute326 = new Attribute("MaxFFT_Y"); 
	public static Attribute Attribute327 = new Attribute("MaxFFT_Z"); 
	public static Attribute Attribute328 = new Attribute("FilMaxFFT_X"); 
	public static Attribute Attribute329 = new Attribute("FilMaxFFT_Z"); 
	public static Attribute Attribute330 = new Attribute("FilMaxFFT_Y"); 
	public static Attribute Attribute331 = new Attribute("high_pass_median_xz"); 
	public static Attribute Attribute332 = new Attribute("high_pass_min_xz"); 
	public static Attribute Attribute333 = new Attribute("high_pass_minima_x"); 
	public static Attribute Attribute334 = new Attribute("high_pass_minima_y"); 
	public static Attribute Attribute335 = new Attribute("high_pass_maxfft_x"); 
	public static Attribute Attribute336 = new Attribute("high_pass_maxfft_y"); 
	public static Attribute Attribute337 = new Attribute("high_pass_maxfft_z"); 
	public static Attribute Attribute338 = new Attribute("high_pass_maxima_x"); 
	public static Attribute Attribute339 = new Attribute("high_pass_maxima_y"); 
	public static Attribute Attribute340 = new Attribute("high_pass_maxima_z"); 
	public static Attribute Attribute341 = new Attribute("high_pass_pt2stdaway_y"); 
	public static Attribute Attribute342 = new Attribute("high_pass_minima_z"); 
	public static Attribute Attribute343 = new Attribute("high_pass_pt2stdaway_z"); 
	public static Attribute Attribute344 = new Attribute("high_pass_x"); 
	public static Attribute Attribute345 = new Attribute("high_pass_std_y"); 
	public static Attribute Attribute346 = new Attribute("high_pass_z"); 
	public static Attribute Attribute347 = new Attribute("high_pass_pt1stdaway_x"); 
	public static Attribute Attribute348 = new Attribute("high_pass_pt1stdaway_y"); 
	public static Attribute Attribute349 = new Attribute("high_pass_pt1stdaway_z"); 
	public static Attribute Attribute350 = new Attribute("high_pass_pt2stdaway_x");
	public static FastVector fvClassVal = new FastVector(3);	
	public static Attribute ClassAttribute;// = new Attribute("Class_label", fvClassVal);
	public static  FastVector fvWekaAttributes = new FastVector(351);
	
	public static Classifier loadModel() {
		 fvClassVal.addElement("1");
		 fvClassVal.addElement("0");
		 fvClassVal.addElement("-1");
		 ClassAttribute = new Attribute("Class_label", fvClassVal);
		 
		 fvWekaAttributes.addElement(Attribute1);
		 fvWekaAttributes.addElement(Attribute2);
		 fvWekaAttributes.addElement(Attribute3);
		 fvWekaAttributes.addElement(Attribute4);
		 fvWekaAttributes.addElement(Attribute5);
		 fvWekaAttributes.addElement(Attribute6);
		 fvWekaAttributes.addElement(Attribute7);
		 fvWekaAttributes.addElement(Attribute8);
		 fvWekaAttributes.addElement(Attribute9);
		 fvWekaAttributes.addElement(Attribute10);
		 fvWekaAttributes.addElement(Attribute11);
		 fvWekaAttributes.addElement(Attribute12);
		 fvWekaAttributes.addElement(Attribute13);
		 fvWekaAttributes.addElement(Attribute14);
		 fvWekaAttributes.addElement(Attribute15);
		 fvWekaAttributes.addElement(Attribute16);
		 fvWekaAttributes.addElement(Attribute17);
		 fvWekaAttributes.addElement(Attribute18);
		 fvWekaAttributes.addElement(Attribute19);
		 fvWekaAttributes.addElement(Attribute20);
		 fvWekaAttributes.addElement(Attribute21);
		 fvWekaAttributes.addElement(Attribute22);
		 fvWekaAttributes.addElement(Attribute23);
		 fvWekaAttributes.addElement(Attribute24);
		 fvWekaAttributes.addElement(Attribute25);
		 fvWekaAttributes.addElement(Attribute26);
		 fvWekaAttributes.addElement(Attribute27);
		 fvWekaAttributes.addElement(Attribute28);
		 fvWekaAttributes.addElement(Attribute29);
		 fvWekaAttributes.addElement(Attribute30);
		 fvWekaAttributes.addElement(Attribute31);
		 fvWekaAttributes.addElement(Attribute32);
		 fvWekaAttributes.addElement(Attribute33);
		 fvWekaAttributes.addElement(Attribute34);
		 fvWekaAttributes.addElement(Attribute35);
		 fvWekaAttributes.addElement(Attribute36);
		 fvWekaAttributes.addElement(Attribute37);
		 fvWekaAttributes.addElement(Attribute38);
		 fvWekaAttributes.addElement(Attribute39);
		 fvWekaAttributes.addElement(Attribute40);
		 fvWekaAttributes.addElement(Attribute41);
		 fvWekaAttributes.addElement(Attribute42);
		 fvWekaAttributes.addElement(Attribute43);
		 fvWekaAttributes.addElement(Attribute44);
		 fvWekaAttributes.addElement(Attribute45);
		 fvWekaAttributes.addElement(Attribute46);
		 fvWekaAttributes.addElement(Attribute47);
		 fvWekaAttributes.addElement(Attribute48);
		 fvWekaAttributes.addElement(Attribute49);
		 fvWekaAttributes.addElement(Attribute50);
		 fvWekaAttributes.addElement(Attribute51);
		 fvWekaAttributes.addElement(Attribute52);
		 fvWekaAttributes.addElement(Attribute53);
		 fvWekaAttributes.addElement(Attribute54);
		 fvWekaAttributes.addElement(Attribute55);
		 fvWekaAttributes.addElement(Attribute56);
		 fvWekaAttributes.addElement(Attribute57);
		 fvWekaAttributes.addElement(Attribute58);
		 fvWekaAttributes.addElement(Attribute59);
		 fvWekaAttributes.addElement(Attribute60);
		 fvWekaAttributes.addElement(Attribute61);
		 fvWekaAttributes.addElement(Attribute62);
		 fvWekaAttributes.addElement(Attribute63);
		 fvWekaAttributes.addElement(Attribute64);
		 fvWekaAttributes.addElement(Attribute65);
		 fvWekaAttributes.addElement(Attribute66);
		 fvWekaAttributes.addElement(Attribute67);
		 fvWekaAttributes.addElement(Attribute68);
		 fvWekaAttributes.addElement(Attribute69);
		 fvWekaAttributes.addElement(Attribute70);
		 fvWekaAttributes.addElement(Attribute71);
		 fvWekaAttributes.addElement(Attribute72);
		 fvWekaAttributes.addElement(Attribute73);
		 fvWekaAttributes.addElement(Attribute74);
		 fvWekaAttributes.addElement(Attribute75);
		 fvWekaAttributes.addElement(Attribute76);
		 fvWekaAttributes.addElement(Attribute77);
		 fvWekaAttributes.addElement(Attribute78);
		 fvWekaAttributes.addElement(Attribute79);
		 fvWekaAttributes.addElement(Attribute80);
		 fvWekaAttributes.addElement(Attribute81);
		 fvWekaAttributes.addElement(Attribute82);
		 fvWekaAttributes.addElement(Attribute83);
		 fvWekaAttributes.addElement(Attribute84);
		 fvWekaAttributes.addElement(Attribute85);
		 fvWekaAttributes.addElement(Attribute86);
		 fvWekaAttributes.addElement(Attribute87);
		 fvWekaAttributes.addElement(Attribute88);
		 fvWekaAttributes.addElement(Attribute89);
		 fvWekaAttributes.addElement(Attribute90);
		 fvWekaAttributes.addElement(Attribute91);
		 fvWekaAttributes.addElement(Attribute92);
		 fvWekaAttributes.addElement(Attribute93);
		 fvWekaAttributes.addElement(Attribute94);
		 fvWekaAttributes.addElement(Attribute95);
		 fvWekaAttributes.addElement(Attribute96);
		 fvWekaAttributes.addElement(Attribute97);
		 fvWekaAttributes.addElement(Attribute98);
		 fvWekaAttributes.addElement(Attribute99);
		 fvWekaAttributes.addElement(Attribute100);
		 fvWekaAttributes.addElement(Attribute101);
		 fvWekaAttributes.addElement(Attribute102);
		 fvWekaAttributes.addElement(Attribute103);
		 fvWekaAttributes.addElement(Attribute104);
		 fvWekaAttributes.addElement(Attribute105);
		 fvWekaAttributes.addElement(Attribute106);
		 fvWekaAttributes.addElement(Attribute107);
		 fvWekaAttributes.addElement(Attribute108);
		 fvWekaAttributes.addElement(Attribute109);
		 fvWekaAttributes.addElement(Attribute110);
		 fvWekaAttributes.addElement(Attribute111);
		 fvWekaAttributes.addElement(Attribute112);
		 fvWekaAttributes.addElement(Attribute113);
		 fvWekaAttributes.addElement(Attribute114);
		 fvWekaAttributes.addElement(Attribute115);
		 fvWekaAttributes.addElement(Attribute116);
		 fvWekaAttributes.addElement(Attribute117);
		 fvWekaAttributes.addElement(Attribute118);
		 fvWekaAttributes.addElement(Attribute119);
		 fvWekaAttributes.addElement(Attribute120);
		 fvWekaAttributes.addElement(Attribute121);
		 fvWekaAttributes.addElement(Attribute122);
		 fvWekaAttributes.addElement(Attribute123);
		 fvWekaAttributes.addElement(Attribute124);
		 fvWekaAttributes.addElement(Attribute125);
		 fvWekaAttributes.addElement(Attribute126);
		 fvWekaAttributes.addElement(Attribute127);
		 fvWekaAttributes.addElement(Attribute128);
		 fvWekaAttributes.addElement(Attribute129);
		 fvWekaAttributes.addElement(Attribute130);
		 fvWekaAttributes.addElement(Attribute131);
		 fvWekaAttributes.addElement(Attribute132);
		 fvWekaAttributes.addElement(Attribute133);
		 fvWekaAttributes.addElement(Attribute134);
		 fvWekaAttributes.addElement(Attribute135);
		 fvWekaAttributes.addElement(Attribute136);
		 fvWekaAttributes.addElement(Attribute137);
		 fvWekaAttributes.addElement(Attribute138);
		 fvWekaAttributes.addElement(Attribute139);
		 fvWekaAttributes.addElement(Attribute140);
		 fvWekaAttributes.addElement(Attribute141);
		 fvWekaAttributes.addElement(Attribute142);
		 fvWekaAttributes.addElement(Attribute143);
		 fvWekaAttributes.addElement(Attribute144);
		 fvWekaAttributes.addElement(Attribute145);
		 fvWekaAttributes.addElement(Attribute146);
		 fvWekaAttributes.addElement(Attribute147);
		 fvWekaAttributes.addElement(Attribute148);
		 fvWekaAttributes.addElement(Attribute149);
		 fvWekaAttributes.addElement(Attribute150);
		 fvWekaAttributes.addElement(Attribute151);
		 fvWekaAttributes.addElement(Attribute152);
		 fvWekaAttributes.addElement(Attribute153);
		 fvWekaAttributes.addElement(Attribute154);
		 fvWekaAttributes.addElement(Attribute155);
		 fvWekaAttributes.addElement(Attribute156);
		 fvWekaAttributes.addElement(Attribute157);
		 fvWekaAttributes.addElement(Attribute158);
		 fvWekaAttributes.addElement(Attribute159);
		 fvWekaAttributes.addElement(Attribute160);
		 fvWekaAttributes.addElement(Attribute161);
		 fvWekaAttributes.addElement(Attribute162);
		 fvWekaAttributes.addElement(Attribute163);
		 fvWekaAttributes.addElement(Attribute164);
		 fvWekaAttributes.addElement(Attribute165);
		 fvWekaAttributes.addElement(Attribute166);
		 fvWekaAttributes.addElement(Attribute167);
		 fvWekaAttributes.addElement(Attribute168);
		 fvWekaAttributes.addElement(Attribute169);
		 fvWekaAttributes.addElement(Attribute170);
		 fvWekaAttributes.addElement(Attribute171);
		 fvWekaAttributes.addElement(Attribute172);
		 fvWekaAttributes.addElement(Attribute173);
		 fvWekaAttributes.addElement(Attribute174);
		 fvWekaAttributes.addElement(Attribute175);
		 fvWekaAttributes.addElement(Attribute176);
		 fvWekaAttributes.addElement(Attribute177);
		 fvWekaAttributes.addElement(Attribute178);
		 fvWekaAttributes.addElement(Attribute179);
		 fvWekaAttributes.addElement(Attribute180);
		 fvWekaAttributes.addElement(Attribute181);
		 fvWekaAttributes.addElement(Attribute182);
		 fvWekaAttributes.addElement(Attribute183);
		 fvWekaAttributes.addElement(Attribute184);
		 fvWekaAttributes.addElement(Attribute185);
		 fvWekaAttributes.addElement(Attribute186);
		 fvWekaAttributes.addElement(Attribute187);
		 fvWekaAttributes.addElement(Attribute188);
		 fvWekaAttributes.addElement(Attribute189);
		 fvWekaAttributes.addElement(Attribute190);
		 fvWekaAttributes.addElement(Attribute191);
		 fvWekaAttributes.addElement(Attribute192);
		 fvWekaAttributes.addElement(Attribute193);
		 fvWekaAttributes.addElement(Attribute194);
		 fvWekaAttributes.addElement(Attribute195);
		 fvWekaAttributes.addElement(Attribute196);
		 fvWekaAttributes.addElement(Attribute197);
		 fvWekaAttributes.addElement(Attribute198);
		 fvWekaAttributes.addElement(Attribute199);
		 fvWekaAttributes.addElement(Attribute200);
		 fvWekaAttributes.addElement(Attribute201);
		 fvWekaAttributes.addElement(Attribute202);
		 fvWekaAttributes.addElement(Attribute203);
		 fvWekaAttributes.addElement(Attribute204);
		 fvWekaAttributes.addElement(Attribute205);
		 fvWekaAttributes.addElement(Attribute206);
		 fvWekaAttributes.addElement(Attribute207);
		 fvWekaAttributes.addElement(Attribute208);
		 fvWekaAttributes.addElement(Attribute209);
		 fvWekaAttributes.addElement(Attribute210);
		 fvWekaAttributes.addElement(Attribute211);
		 fvWekaAttributes.addElement(Attribute212);
		 fvWekaAttributes.addElement(Attribute213);
		 fvWekaAttributes.addElement(Attribute214);
		 fvWekaAttributes.addElement(Attribute215);
		 fvWekaAttributes.addElement(Attribute216);
		 fvWekaAttributes.addElement(Attribute217);
		 fvWekaAttributes.addElement(Attribute218);
		 fvWekaAttributes.addElement(Attribute219);
		 fvWekaAttributes.addElement(Attribute220);
		 fvWekaAttributes.addElement(Attribute221);
		 fvWekaAttributes.addElement(Attribute222);
		 fvWekaAttributes.addElement(Attribute223);
		 fvWekaAttributes.addElement(Attribute224);
		 fvWekaAttributes.addElement(Attribute225);
		 fvWekaAttributes.addElement(Attribute226);
		 fvWekaAttributes.addElement(Attribute227);
		 fvWekaAttributes.addElement(Attribute228);
		 fvWekaAttributes.addElement(Attribute229);
		 fvWekaAttributes.addElement(Attribute230);
		 fvWekaAttributes.addElement(Attribute231);
		 fvWekaAttributes.addElement(Attribute232);
		 fvWekaAttributes.addElement(Attribute233);
		 fvWekaAttributes.addElement(Attribute234);
		 fvWekaAttributes.addElement(Attribute235);
		 fvWekaAttributes.addElement(Attribute236);
		 fvWekaAttributes.addElement(Attribute237);
		 fvWekaAttributes.addElement(Attribute238);
		 fvWekaAttributes.addElement(Attribute239);
		 fvWekaAttributes.addElement(Attribute240);
		 fvWekaAttributes.addElement(Attribute241);
		 fvWekaAttributes.addElement(Attribute242);
		 fvWekaAttributes.addElement(Attribute243);
		 fvWekaAttributes.addElement(Attribute244);
		 fvWekaAttributes.addElement(Attribute245);
		 fvWekaAttributes.addElement(Attribute246);
		 fvWekaAttributes.addElement(Attribute247);
		 fvWekaAttributes.addElement(Attribute248);
		 fvWekaAttributes.addElement(Attribute249);
		 fvWekaAttributes.addElement(Attribute250);
		 fvWekaAttributes.addElement(Attribute251);
		 fvWekaAttributes.addElement(Attribute252);
		 fvWekaAttributes.addElement(Attribute253);
		 fvWekaAttributes.addElement(Attribute254);
		 fvWekaAttributes.addElement(Attribute255);
		 fvWekaAttributes.addElement(Attribute256);
		 fvWekaAttributes.addElement(Attribute257);
		 fvWekaAttributes.addElement(Attribute258);
		 fvWekaAttributes.addElement(Attribute259);
		 fvWekaAttributes.addElement(Attribute260);
		 fvWekaAttributes.addElement(Attribute261);
		 fvWekaAttributes.addElement(Attribute262);
		 fvWekaAttributes.addElement(Attribute263);
		 fvWekaAttributes.addElement(Attribute264);
		 fvWekaAttributes.addElement(Attribute265);
		 fvWekaAttributes.addElement(Attribute266);
		 fvWekaAttributes.addElement(Attribute267);
		 fvWekaAttributes.addElement(Attribute268);
		 fvWekaAttributes.addElement(Attribute269);
		 fvWekaAttributes.addElement(Attribute270);
		 fvWekaAttributes.addElement(Attribute271);
		 fvWekaAttributes.addElement(Attribute272);
		 fvWekaAttributes.addElement(Attribute273);
		 fvWekaAttributes.addElement(Attribute274);
		 fvWekaAttributes.addElement(Attribute275);
		 fvWekaAttributes.addElement(Attribute276);
		 fvWekaAttributes.addElement(Attribute277);
		 fvWekaAttributes.addElement(Attribute278);
		 fvWekaAttributes.addElement(Attribute279);
		 fvWekaAttributes.addElement(Attribute280);
		 fvWekaAttributes.addElement(Attribute281);
		 fvWekaAttributes.addElement(Attribute282);
		 fvWekaAttributes.addElement(Attribute283);
		 fvWekaAttributes.addElement(Attribute284);
		 fvWekaAttributes.addElement(Attribute285);
		 fvWekaAttributes.addElement(Attribute286);
		 fvWekaAttributes.addElement(Attribute287);
		 fvWekaAttributes.addElement(Attribute288);
		 fvWekaAttributes.addElement(Attribute289);
		 fvWekaAttributes.addElement(Attribute290);
		 fvWekaAttributes.addElement(Attribute291);
		 fvWekaAttributes.addElement(Attribute292);
		 fvWekaAttributes.addElement(Attribute293);
		 fvWekaAttributes.addElement(Attribute294);
		 fvWekaAttributes.addElement(Attribute295);
		 fvWekaAttributes.addElement(Attribute296);
		 fvWekaAttributes.addElement(Attribute297);
		 fvWekaAttributes.addElement(Attribute298);
		 fvWekaAttributes.addElement(Attribute299);
		 fvWekaAttributes.addElement(Attribute300);
		 fvWekaAttributes.addElement(Attribute301);
		 fvWekaAttributes.addElement(Attribute302);
		 fvWekaAttributes.addElement(Attribute303);
		 fvWekaAttributes.addElement(Attribute304);
		 fvWekaAttributes.addElement(Attribute305);
		 fvWekaAttributes.addElement(Attribute306);
		 fvWekaAttributes.addElement(Attribute307);
		 fvWekaAttributes.addElement(Attribute308);
		 fvWekaAttributes.addElement(Attribute309);
		 fvWekaAttributes.addElement(Attribute310);
		 fvWekaAttributes.addElement(Attribute311);
		 fvWekaAttributes.addElement(Attribute312);
		 fvWekaAttributes.addElement(Attribute313);
		 fvWekaAttributes.addElement(Attribute314);
		 fvWekaAttributes.addElement(Attribute315);
		 fvWekaAttributes.addElement(Attribute316);
		 fvWekaAttributes.addElement(Attribute317);
		 fvWekaAttributes.addElement(Attribute318);
		 fvWekaAttributes.addElement(Attribute319);
		 fvWekaAttributes.addElement(Attribute320);
		 fvWekaAttributes.addElement(Attribute321);
		 fvWekaAttributes.addElement(Attribute322);
		 fvWekaAttributes.addElement(Attribute323);
		 fvWekaAttributes.addElement(Attribute324);
		 fvWekaAttributes.addElement(Attribute325);
		 fvWekaAttributes.addElement(Attribute326);
		 fvWekaAttributes.addElement(Attribute327);
		 fvWekaAttributes.addElement(Attribute328);
		 fvWekaAttributes.addElement(Attribute329);
		 fvWekaAttributes.addElement(Attribute330);
		 fvWekaAttributes.addElement(Attribute331);
		 fvWekaAttributes.addElement(Attribute332);
		 fvWekaAttributes.addElement(Attribute333);
		 fvWekaAttributes.addElement(Attribute334);
		 fvWekaAttributes.addElement(Attribute335);
		 fvWekaAttributes.addElement(Attribute336);
		 fvWekaAttributes.addElement(Attribute337);
		 fvWekaAttributes.addElement(Attribute338);
		 fvWekaAttributes.addElement(Attribute339);
		 fvWekaAttributes.addElement(Attribute340);
		 fvWekaAttributes.addElement(Attribute341);
		 fvWekaAttributes.addElement(Attribute342);
		 fvWekaAttributes.addElement(Attribute343);
		 fvWekaAttributes.addElement(Attribute344);
		 fvWekaAttributes.addElement(Attribute345);
		 fvWekaAttributes.addElement(Attribute346);
		 fvWekaAttributes.addElement(Attribute347);
		 fvWekaAttributes.addElement(Attribute348);
		 fvWekaAttributes.addElement(Attribute349);
		 fvWekaAttributes.addElement(Attribute350);
		 fvWekaAttributes.addElement(ClassAttribute);
		 
		 
		try {

            InputStream is =  MainActivity.assetManager.open("SMOModel.model");
            ObjectInputStream ois = new ObjectInputStream(is);
            c = (Classifier) ois.readObject();
			ois.close();
		//	Log.i("MappingRoadConditions","classifier options"+c.getOptions()[0]);
			return c;
		} catch (Exception e) {
		//	Log.i("MappingRoadConditions", e.toString());
			return null;
		}
	}
	public synchronized int classify(Feature f)
	{

        Instances e = new Instances("Rel", fvWekaAttributes, 351);
        e.setClassIndex(350);

		Instance iExample = new Instance(351);
        iExample.setDataset(e);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(0),	f.Std_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(1), f.Std_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(2), f.Std_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(3), f.Pt1stdaway_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(4), f.Pt1stdaway_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(5), f.Pt1stdaway_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(6), f.Pt2stdaway_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(7), f.Pt2stdaway_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(8), f.Pt2stdaway_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(9), f.Maxima_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(10), f.Maxima_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(11), f.Maxima_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(12), f.Minima_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(13), f.Minima_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(14), f.Minima_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(15), f.MinSpeed);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(16), f.MaxSpeed);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(17), f.FilMaxima_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(18), f.FilMaxima_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(19), f.FilMaxima_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(20), f.FilMinima_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(21), f.FilMinima_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(22), f.FilMinima_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(23), f.FilStd_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(24), f.FilStd_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(25), f.FilStd_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(26), f.FilPt1stdaway_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(27), f.FilPt1stdaway_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(28), f.FilPt2stdaway_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(29), f.FilPt2stdaway_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(30), f.FilPt2stdaway_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(31), f.FilPt1stdaway_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(32), f.AvSpeed);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(33), f.FilFFT_Z_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(34), f.FilFFT_Z_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(35), f.FilFFT_Z_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(36), f.FilFFT_Z_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(37), f.FilFFT_Z_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(38), f.FilFFT_Z_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(39), f.FilFFT_Z_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(40), f.FilFFT_Z_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(41), f.FilFFT_Z_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(42), f.FilFFT_Z_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(43), f.FilFFT_Z_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(44), f.FilFFT_Z_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(45), f.FilFFT_Z_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(46), f.FilFFT_Z_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(47), f.FilFFT_Z_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(48), f.FilFFT_Z_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(49), f.FilFFT_Z_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(50), f.FilFFT_Z_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(51), f.FilFFT_Z_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(52), f.FilFFT_Z_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(53), f.FilFFT_Z_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(54), f.FilFFT_Z_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(55), f.FilFFT_Z_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(56), f.FilFFT_Z_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(57), f.FilFFT_Z_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(58), f.FilFFT_Z_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(59), f.FilFFT_Z_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(60), f.FilFFT_Z_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(61), f.FilFFT_Z_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(62), f.FilFFT_Z_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(63), f.FilFFT_Z_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(64), f.FilFFT_Z_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(65), f.FilFFT_Z_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(66), f.FilFFT_Z_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(67), f.FilFFT_Z_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(68), f.FilFFT_Z_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(69), f.FilFFT_Z_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(70), f.FilFFT_Z_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(71), f.FilFFT_Z_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(72), f.FilFFT_Z_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(73), f.FilFFT_Z_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(74), f.FilFFT_Z_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(75), f.FilFFT_Z_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(76), f.FilFFT_Z_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(77), f.FilFFT_Z_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(78), f.FilFFT_Z_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(79), f.FilFFT_Z_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(80), f.FFT_X_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(81), f.FFT_X_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(82), f.FFT_X_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(83), f.FFT_X_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(84), f.FFT_X_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(85), f.FFT_X_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(86), f.FFT_X_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(87), f.FFT_X_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(88), f.FFT_X_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(89), f.FFT_X_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(90), f.FFT_X_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(91), f.FFT_X_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(92), f.FFT_X_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(93), f.FFT_X_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(94), f.FFT_X_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(95), f.FFT_X_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(96), f.FFT_X_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(97), f.FFT_X_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(98), f.FFT_X_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(99), f.FFT_X_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(100),f.FFT_X_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(101),f.FFT_X_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(102),f.FFT_X_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(103),f.FFT_X_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(104),f.FFT_X_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(105),f.FFT_X_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(106),f.FFT_X_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(107),f.FFT_X_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(108),f.FFT_X_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(109),f.FFT_X_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(110),f.FFT_X_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(111),f.FFT_X_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(112),f.FFT_X_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(113),f.FFT_X_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(114),f.FFT_X_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(115),f.FFT_X_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(116),f.FFT_X_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(117),f.FFT_X_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(118),f.FFT_X_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(119),f.FFT_X_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(120),f.FFT_X_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(121),f.FFT_X_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(122),f.FFT_X_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(123),f.FFT_X_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(124),f.FFT_X_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(125),f.FFT_X_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(126),f.FFT_X_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(127),f.FFT_X_48);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(128),f.FFT_X_49);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(129),f.FilFFT_Y_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(130),f.FilFFT_Y_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(131),f.FilFFT_Y_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(132),f.FilFFT_Y_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(133),f.FilFFT_Y_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(134),f.FilFFT_Y_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(135),f.FilFFT_Y_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(136),f.FilFFT_Y_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(137),f.FilFFT_Y_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(138),f.FilFFT_Y_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(139),f.FilFFT_Y_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(140),f.FilFFT_Y_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(141),f.FilFFT_Y_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(142),f.FilFFT_Y_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(143),f.FilFFT_Y_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(144),f.FilFFT_Y_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(145),f.FilFFT_Y_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(146),f.FilFFT_Y_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(147),f.FilFFT_Y_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(148),f.FilFFT_Y_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(149),f.FilFFT_Y_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(150),f.FilFFT_Y_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(151),f.FilFFT_Y_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(152),f.FilFFT_Y_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(153),f.FilFFT_Y_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(154),f.FilFFT_Y_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(155),f.FilFFT_Y_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(156),f.FilFFT_Y_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(157),f.FilFFT_Y_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(158),f.FilFFT_Y_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(159),f.FilFFT_Y_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(160),f.FilFFT_Y_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(161),f.FilFFT_Y_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(162),f.FilFFT_Y_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(163),f.FilFFT_Y_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(164),f.FilFFT_Y_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(165),f.FilFFT_Y_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(166),f.FilFFT_Y_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(167),f.FilFFT_Y_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(168),f.FilFFT_Y_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(169),f.FilFFT_Y_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(170),f.FilFFT_Y_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(171),f.FilFFT_Y_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(172),f.FilFFT_Y_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(173),f.FilFFT_Y_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(174),f.FilFFT_Y_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(175),f.FilFFT_Y_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(176),f.FilFFT_Y_48);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(177),f.FilFFT_Y_49);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(178),f.FilFFT_X_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(179),f.FilFFT_X_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(180),f.FilFFT_X_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(181),f.FilFFT_X_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(182),f.FilFFT_X_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(183),f.FilFFT_X_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(184),f.FilFFT_X_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(185),f.FilFFT_X_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(186),f.FilFFT_X_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(187),f.FilFFT_X_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(188),f.FilFFT_X_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(189),f.FilFFT_X_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(190),f.FilFFT_X_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(191),f.FilFFT_X_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(192),f.FilFFT_X_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(193),f.FilFFT_X_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(194),f.FilFFT_X_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(195),f.FilFFT_X_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(196),f.FilFFT_X_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(197),f.FilFFT_X_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(198),f.FilFFT_X_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(199),f.FilFFT_X_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(200),f.FilFFT_X_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(201),f.FilFFT_X_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(202),f.FilFFT_X_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(203),f.FilFFT_X_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(204),f.FilFFT_X_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(205),f.FilFFT_X_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(206),f.FilFFT_X_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(207),f.FilFFT_X_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(208),f.FilFFT_X_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(209),f.FilFFT_X_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(210),f.FilFFT_X_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(211),f.FilFFT_X_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(212),f.FilFFT_X_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(213),f.FilFFT_X_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(214),f.FilFFT_X_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(215),f.FilFFT_X_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(216),f.FilFFT_X_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(217),f.FilFFT_X_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(218),f.FilFFT_X_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(219),f.FilFFT_X_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(220),f.FilFFT_X_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(221),f.FilFFT_X_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(222),f.FilFFT_X_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(223),f.FilFFT_X_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(224),f.FilFFT_X_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(225),f.FilFFT_X_48);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(226),f.FFT_Y_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(227),f.FFT_Y_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(228),f.FFT_Y_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(229),f.FFT_Y_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(230),f.FFT_Y_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(231),f.FFT_Y_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(232),f.FFT_Y_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(233),f.FFT_Y_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(234),f.FFT_Y_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(235),f.FFT_Y_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(236),f.FFT_Y_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(237),f.FFT_Y_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(238),f.FFT_Y_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(239),f.FFT_Y_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(240),f.FFT_Y_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(241),f.FFT_Y_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(242),f.FFT_Y_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(243),f.FFT_Y_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(244),f.FFT_Y_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(245),f.FFT_Y_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(246),f.FFT_Y_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(247),f.FFT_Y_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(248),f.FFT_Y_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(249),f.FFT_Y_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(250),f.FFT_Y_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(251),f.FFT_Y_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(252),f.FFT_Y_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(253),f.FFT_Y_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(254),f.FFT_Y_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(255),f.FFT_Y_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(256),f.FFT_Y_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(257),f.FFT_Y_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(258),f.FFT_Y_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(259),f.FFT_Y_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(260),f.FFT_Y_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(261),f.FFT_Y_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(262),f.FFT_Y_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(263),f.FFT_Y_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(264),f.FFT_Y_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(265),f.FFT_Y_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(266),f.FFT_Y_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(267),f.FFT_Y_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(268),f.FFT_Y_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(269),f.FFT_Y_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(270),f.FFT_Y_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(271),f.FFT_Y_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(272),f.FFT_Y_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(273),f.FFT_Y_48);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(274),f.FFT_Y_49);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(275),f.FFT_Z_1);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(276),f.FFT_Z_2);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(277),f.FFT_Z_3);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(278),f.FFT_Z_4);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(279),f.FFT_Z_5);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(280),f.FFT_Z_6);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(281),f.FFT_Z_7);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(282),f.FFT_Z_8);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(283),f.FFT_Z_9);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(284),f.FFT_Z_10);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(285),f.FFT_Z_11);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(286),f.FFT_Z_12);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(287),f.FFT_Z_13);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(288),f.FFT_Z_14);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(289),f.FFT_Z_15);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(290),f.FFT_Z_16);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(291),f.FFT_Z_17);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(292),f.FFT_Z_18);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(293),f.FFT_Z_19);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(294),f.FFT_Z_20);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(295),f.FFT_Z_21);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(296),f.FFT_Z_22);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(297),f.FFT_Z_23);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(298),f.FFT_Z_24);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(299),f.FFT_Z_25);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(300),f.FFT_Z_26);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(301),f.FFT_Z_27);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(302),f.FFT_Z_28);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(303),f.FFT_Z_29);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(304),f.FFT_Z_30);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(305),f.FFT_Z_31);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(306),f.FFT_Z_32);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(307),f.FFT_Z_33);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(308),f.FFT_Z_34);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(309),f.FFT_Z_35);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(310),f.FFT_Z_36);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(311),f.FFT_Z_37);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(312),f.FFT_Z_38);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(313),f.FFT_Z_39);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(314),f.FFT_Z_40);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(315),f.FFT_Z_41);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(316),f.FFT_Z_42);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(317),f.FFT_Z_43);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(318),f.FFT_Z_44);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(319),f.FFT_Z_45);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(320),f.FFT_Z_46);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(321),f.FFT_Z_47);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(322),f.FFT_Z_48);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(323),f.FFT_Z_49);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(324),f.MaxFFT_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(325),f.MaxFFT_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(326),f.MaxFFT_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(327),f.FilMaxFFT_X);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(328),f.FilMaxFFT_Z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(329),f.FilMaxFFT_Y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(330),f.high_pass_median_xz);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(331),f.high_pass_min_xz);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(332),f.high_pass_minima_x);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(333),f.high_pass_minima_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(334),f.high_pass_maxfft_x);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(335),f.high_pass_maxfft_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(336),f.high_pass_maxfft_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(337),f.high_pass_maxima_x);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(338),f.high_pass_maxima_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(339),f.high_pass_maxima_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(340),f.high_pass_pt2stdaway_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(341),f.high_pass_minima_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(342),f.high_pass_pt2stdaway_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(343),f.high_pass_x);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(344),f.high_pass_std_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(345),f.high_pass_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(346),f.high_pass_pt1stdaway_x);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(347),f.high_pass_pt1stdaway_y);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(348),f.high_pass_pt1stdaway_z);
		iExample.setValue((Attribute)fvWekaAttributes.elementAt(349),f.high_pass_pt2stdaway_x);
	//	Log.i("MappingRoadConditions",iExample.toString(350));

		try {
			double fDistribution = c.classifyInstance(iExample);//distributionForInstance(iExample);
		//	Log.i("MappingRoadConditions", "Class:  " + fvClassVal.elementAt((int)fDistribution));
            return Integer.parseInt((String) fvClassVal.elementAt((int)fDistribution));
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		return 0;
		
	}
}
